/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/Mounten.glb -o src/components/Mounten.jsx -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Mounten(props) {
  const { nodes, materials } = useGLTF("/models/Mounten.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={1}
      position={[-2.5, -6, 135]}
      rotation={[Math.PI / 1, 0, 3.15]}
    >
      <mesh
        geometry={nodes["Terrain_Plane001-Mesh"].geometry}
        material={materials.Grass}
      />
      <mesh
        geometry={nodes["Terrain_Plane001-Mesh_1"].geometry}
        material={materials.Ground}
      />
      <mesh
        geometry={nodes["Terrain_Plane001-Mesh_2"].geometry}
        material={materials.Snow}
      />
    </group>
  );
}

useGLTF.preload("/models/Mounten.glb");
