/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/Road.glb -o src/components/Road.jsx -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Road(props) {
  const { nodes, materials } = useGLTF("/models/Road.glb");
  return (
    <>
      <group
        {...props}
        dispose={null}
        scale={0.09}
        rotation={[0, -1.572, 0]}
        position={[-0, -1, 15]}
      >
        <mesh geometry={nodes.Road.geometry} material={materials.Mat} />
      </group>
      <group
        {...props}
        dispose={null}
        scale={0.09}
        rotation={[0, -1.572, 0]}
        position={[-0, -1, -3]}
      >
        <mesh geometry={nodes.Road.geometry} material={materials.Mat} />
      </group>
    </>
  );
}

useGLTF.preload("/models/Road.glb");
